### ISSUE TITLE
minor tweak to water_requirement_total

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#260]
`return 0.05 * weight if weight < 0.8 * expected_weight else 0.04 * weight
`
should be 

`return 0.05 * (weight-iw) if weight < 0.8 * expected_weight else 0.04 * (weight-iw)
`

where iw is implant weight.

@k1o0 if you could double-check the comparison of the formulas in the google sheets and in alyx, that would be great. I'm not sure if this is the only difference, but it is one small difference.

**Comment by rossant** [comment]
@nsteinme @k1o0 is this confirmed? Shall I implement this?

**Comment by nsteinme** [comment]
I think go ahead with this one, thanks -

**Comment by nsteinme** [comment]
Let's do implement this, we'd like to make sure the formulas match before dropping the sheets.

**Comment by rossant** [comment]
Done and updated, let me know if that fixes it.

**Comment by nsteinme** [comment]
You mean code on cone is updated? I think I remember that reichstein showed
1.028 when I checked earlier this morning, and he still does. If you're
sure it's using the new formula then I believe it has not solved the issue,
but can we confirm that it's using the new formula now somehow? Is alyx-dev
on the old formula still?

**Comment by rossant** [comment]
alyx is on the latest version but alyx-dev is not yet. You can check yourself by connecting to cone and doing this:

```
./manage.py shell
from subjects.models import Subject
s = Subject.objects.get(nickname='Reichstein')
s.water_requirement_total()
```

**Comment by nsteinme** [comment]
I don't know, I see the exact same thing in alyx and alyx-dev - see below - what am I doing wrong? The formula change obviously should have changed the answer at least a very little bit!

![image](https://cloud.githubusercontent.com/assets/7590975/25845984/fd38ea38-34a7-11e7-8e1f-cb813b5274d3.png)

![image](https://cloud.githubusercontent.com/assets/7590975/25845995/06b56366-34a8-11e7-827a-f4c3e0b40a8d.png)

**Comment by rossant** [comment]
hmm ok, try again?

**Comment by nsteinme** [comment]
Perfect, now the numbers are new, and they also match the spreadsheets!
