### ISSUE TITLE
Animal names saved but naming error given when editing litter

### ISSUE THREAD

**Issue by BexTerry** [cortex-lab/alyx#664]
I'm having this issue with a new strain that is nicknamed Ai162g6f.GAD X GAD++
When adding animals into a litter, it generates the names as it should, but when I try and save any changes after then (ear mark, cage ID etc), it gives me a naming error.
![image](https://user-images.githubusercontent.com/55093069/94673249-5e36b080-030e-11eb-8f30-a095c3a1a5e7.png)
![image](https://user-images.githubusercontent.com/55093069/94673311-71498080-030e-11eb-873e-dafc483aef19.png)

Its nickname doesn't use any symbols different to our other strains, so I don't understand why it's having a problem with it

**Comment by rossant** [comment]
should be fixed in next release (so far alyx didn't like nicknames with `+`)

**Comment by BexTerry** [comment]
@rossant it's still not accepting the + in the name

**Comment by rossant** [comment]
Okay perhaps the server hadn't been reloaded, can you try again now?

**Comment by BexTerry** [comment]
still no luck
![image](https://user-images.githubusercontent.com/55093069/96246602-c806b980-0fa0-11eb-9fe4-05cbfb5c058c.png)

the server has been reloaded because the issue with the breeding cages has been fixed (#662)

**Comment by rossant** [comment]
could you please post here the exact name you're trying to input?

**Comment by rossant** [comment]
and the URL too if possible?

**Comment by BexTerry** [comment]
Ai162g6f.GAD X GAD++_0009 
https://alyx.cortexlab.net/admin/subjects/litter/86741512-a769-4dca-90cf-56807e6ee819/change/?_changelist_filters=line__id__exact%3Dfbfc745d-3dce-4ed5-9aab-95b907e2d04b

Is the space in the name also an issue? (I did not create this line)
Thanks!

**Comment by rossant** [comment]
I see, yes spaces are indeed a problem and might cause various issues. How complicated would it be to rename the line and the breeding pairs to replace the space by an underscore?

**Comment by BexTerry** [comment]
ok, I have corrected this issue, thanks for the help!
(there were also semicolons causing an issue, I'll rename everything)
